## Values and References

The value of a variable is stored in the computer's [*random access memory*, or RAM](https://en.wikipedia.org/wiki/Random-access_memory). Think of it as a huge, contiguous list of numbers. When we assign a variable `name = 'Brian'`, the string `Brian` is stored somewhere in this huge list to which the variable `name` refers. The python function `id()` returns an identifier for this *reference*:

In [57]:
name = 'Brian'  # Stores the string 'Brian' and assigns its reference to 'name'
id(name), name  # Get the identifier for this reference.

(2202804543072, 'Brian')

When we assign one variable to another, Python does **not** create a copy. Instead, both variables refer to the same *object* in memory. This design gives Python the efficiency of *not copying objects unnecessarily*.

In [178]:
same_name = name  # Assign the same reference to 'same_name'
id(same_name), same_name  # Note how the reference identifier is the same!

(2202804543072, 'Brian')

The operator `is` is used for comparing references. It can be used to check if two variables truly refer to the same *object*:

In [185]:
a = [1, 2, 3]
b = [1, 2, 3]

if a == b:  # Compare values
    print('Lists a and b have the same values.')
if a is not b:  # Compare references
    print('The lists refer to different objects!')

Lists a and b have the same values.
But a and b are not the same list!


In [186]:
a = [1, 2, 3]
b = a

b[0] = 42  # Modify the list to which b refers.
print(a)  # a and b refer to the same list!

if a is b:  # Compare references
    print('The lists refer to the same object!')

[42, 2, 3]
The lists refer to the same object!


## References and Numpy Arrays
The above applies to all Python objects, including Numpy arrays. Therefore, if we want to create an independent copy of a Numpy array so that we can modify the data without affecting the original, we must explicitly create a copy. This can be done with `np.copy()` or the `.copy()` function of the array itself:

In [176]:
import numpy as np

identity = np.eye(3, 3)  # Create a 3×3 identity matrix.

# 'm' refers to the same object as 'identity', so changing 'm' will change 'identity':
m = identity
m *= 2

print(identity)  # 'identity' is changed!

[[2. 0. 0.]
 [0. 2. 0.]
 [0. 0. 2.]]


In [177]:
identity = np.eye(3, 3)

# Explicitly copy 'identity'. Now 'm' refers to a copy of the values in 'identity':
m = identity.copy()
m *= 2

print(identity)  # 'identity' is not changed.

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


Note that even when we slice an array, the resulting array can still refer to the same underlying data as the original array! In fact, many NumPy operations can return a different *view* of an array without creating a copy of its data. Changes made through such a view may therefore also affect the original array.

In case you're in doubt what the default behavior for a particular Numpy function is, then just check the [Numpy documentation](https://numpy.org/doc/stable/reference/generated/numpy.transpose.html) to be sure. Note how these frequently used functions all return a view on the same underlying data:

In [208]:
original = np.array([[1, 2, 3], [4, 5, 6]])  # Create a 2×3 matrix.

sliced = original[:, :1]  # Get the first column
transposed = original.transpose()  # Transpose (swap axes)
flipped = np.flip(original, axis=1)  # Mirror the second axis (horizontal)
flattened = original.ravel()  # Reshape from 2×3 matrix to a 'flat' array.
reshaped = original.reshape(3, 2)  # Reshape from 2×3 to a 3×2 matrix

original[0, 0] = 99  # Change the first element in the original matrix.

print(f'original:\n {original}\n'
      f'sliced:\n {sliced}\n'
      f'transposed:\n {transposed}\n'
      f'flipped:\n {flipped}\n'
      f'flattened:\n {flattened}\n'
      f'reshaped:\n {reshaped}\n')

original:
 [[99  2  3]
 [ 4  5  6]]
sliced:
 [[99]
 [ 4]]
transposed:
 [[99  4]
 [ 2  5]
 [ 3  6]]
flipped:
 [[ 3  2 99]
 [ 6  5  4]]
flattened:
 [99  2  3  4  5  6]
reshaped:
 [[99  2]
 [ 3  4]
 [ 5  6]]



## Numpy Arrays and Datatypes
So far, we have encountered the numeric Python types `integer` and `float`. These types can represent a wide range of values with high precision. This flexibility comes at a cost, however: higher-precision data types generally require more memory and may slow down computation, because *retrieving data from memory takes time*. This can become particularly important when working with large images, where millions of values need to be stored and processed.

For these reasons, Numpy offers a range of numeric datatypes, with different precision and other properties:

| Operator        | Meaning                         | Range                                                | Precision    |
|-----------------|---------------------------------|------------------------------------------------------|--------------|
| `bool`          | Boolean                         | $\{\text{True}, \text{False}\}$                      | binary       |
| `np.int8`       | 8-bit signed integer            | $[-128, 127]$                                        | integer      |
| `np.uint8`      | 8-bit unsigned integer          | $[0, 255]$                                           | integer      |
| `np.int16`      | 16-bit signed integer           | $[-32768, 32767]$                                    | integer      |
| `np.uint16`     | 16-bit unsigned integer         | $[0, 65535]$                                         | integer      |
| `np.int32`      | 32-bit signed integer           | $[-2^{31}, 2^{31}-1]$                                | integer      |
| `np.uint32`     | 32-bit unsigned integer         | $[0, 2^{32}-1]$                                      | integer      |
| `np.int64`      | 64-bit signed integer           | $[-2^{63}, 2^{63}-1]$                                | integer      |
| `np.uint64`     | 64-bit unsigned integer         | $[0, 2^{64}-1]$                                      | integer      |
| `np.float16`    | 16-bit floating point           | $[-65504, 65504]$                                    | 3-4 digits   |
| `np.float32`    | 32-bit floating point           | $\approx[-3.4 \times 10^{38}, 3.4 \times 10^{38}]$   | ~7 digits    |
| `np.float64`    | 64-bit floating point           | $\approx[-1.8 \times 10^{308}, 1.8 \times 10^{308}]$ | 15-16 digits |
| `np.complex64`  | 2×32-bit complex floating point | $\approx[-3.4 \times 10^{38}, 3.4 \times 10^{38}]$   | ~7 digits    |
| `np.complex128` | 2×64-bit complex floating point | $\approx[-1.8 \times 10^{308}, 1.8 \times 10^{308}]$ | 15-16 digits |

The number of bits indicate how much memory is required to store each value. Eight make up one *byte*, and a million of those is known as a *megabyte*, or MB.
So, storing a 1000×1000 image as `uint8` requires 1 MB, and storing the same image as `int64` requires 8 MB.

'Traditional' image formats (`jpg`, `png`, `gif`) commonly store red, green and blue pixel values as three 8-bit unsigned integers. For many photographs, the $2^8$=256 levels provided by uint8 are sufficient.
Medical images, however, often require higher precision, a sign, and perhaps floating point numbers. The `float32` datatype is therefore a practical and safe choice for many applications. On the contrary, binary segmentation masks could be stored as Boolean values. Segmentation labels (such as 0 for background, 1 for gray matter, 2 for white matter, etc.) could be efficiently stored as uint8.

When creating a new Numpy array, the optional keyword argument `dtype` can be used to specify the datatype explicitly. If it is omitted, Numpy automatically chooses a type that can represent the given values:

In [224]:
rgb = np.array([255, 140, 28], dtype=np.uint8)  # uint8 datatype specified
print(f'{rgb} is stored as {rgb.dtype}')

array = np.array([-1000, 500, 2000])  # Datatype not specified
print(f'{array} is stored as {array.dtype}')

binary_mask = array > 0  # Result from a logical operation
print(f'{binary_mask} is stored as {binary_mask.dtype}')

[255 140  28] is stored as uint8
[-1000   500  2000] is stored as int64
[False  True  True] is stored as bool


 An existing Numpy array can be casted to another datatype using the `.astype()` method. *Use this with caution*, because Numpy will **not** check if all values can be represented in the new datatype. Numbers will not be *clipped* (i.e. rounded to the nearest possible value), but *wrapped*:

In [237]:
array = np.array([-1, 0, 1], dtype=np.int8)  # int8 allows storing signed numbers, such as -1.
array.astype(np.uint8)  # uint8 does not store signed numbers: -1 will be wrapped to (-1 + 256 = 255)!

array([255,   0,   1], dtype=uint8)

In [238]:
array = np.array([254, 255, 256], dtype=np.int16)  # int16 allows storing signed numbers up to 32676
array.astype(np.uint8)  # the maximum value of a uint8 is 255: 256 will be wrapped to (256 - 256 = 0)!

array([254, 255,   0], dtype=uint8)

If you would like to clip values, you should do that explicitly:

In [232]:
array = np.array([-1, 0, 1], dtype=np.int8)  # int8 allows storing signed numbers, such as -1.
array.clip(0, 255).astype(np.uint8)  # Clip to the range supported by uint8

array([0, 0, 1], dtype=uint8)

Wrapping also occurs in calculations, so make sure that the chosen datatype is appropriate for the image processing that you have in mind:

In [258]:
array = np.array([0, 50, 200], dtype=np.uint8)  # the maximum value of a uint8 is 255
array * 4  # 400 will be wrapped to (800 - 3×256 = 144):

array([  0, 200,  32], dtype=uint8)

In [254]:
array = np.array([0, 100, 200], dtype=np.float32)  # float32 is a practical and safe choice for many applications
(array ** 4) / 3 - 1000  # float32 has a sufficient range and precision:

array([-1.0000000e+03,  3.3332334e+07,  5.3333235e+08], dtype=float32)

## Assignments
You've reached the end of this week's study material! During Friday's practical session, you can work on this week's assignment, which can be found in the [course materials](#course-materials).